# This is a file used by the Cargo build script to identify where to get resources
# and other various tidbits.
# Usually, you don't need to change this unless link rot happened or something broke significantly

[cowsay]
source-zip-url = "https://github.com/cowsay-org/cowsay/archive/refs/heads/main.zip"
resource-location = "cowsay-main/share/cowsay/cows"
exclude = ["three-eyes.cow", "udder.cow"]

[fortune-mod]
source-zip-url = "https://github.com/shlomif/fortune-mod/archive/refs/heads/master.zip"
resource-location = "fortune-mod-master/fortune-mod/datfiles"

[settings]
# max-fortune-line-len = 40
# max-fortune-lines = 2
